POST http://localhost:3000/api/members
Content-Type: application/json

{
    "name": "Sample",
    "position": "Developer",
    "hp": "200",
    "picture": "https://storage.googleapis.com/gg-member-photos/mateo-m.png",
    "favoriteGames": "CS2, Valorant, Escape From Tarkov",
    "aboutMe": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor, est vel blandit tempor, urna nisi pellentesque nisl, vitae consequat sapien nisl at tellus."
}